### PR TITLE
Me Gyro fixes & inconsistent version numbers

### PR DESCRIPTION
**Pull request by clplaneguy**

### CODE REVIEW

**Comment by VorpalBlade** [comment]
Hm, did you mean to submit this to the upstream Makeblock-official (not that they seem to care about pull requests)? I'd like some context for what this patch tries to accomplish though.

**Comment by clplaneguy** [comment]
MakeBlock claims to be a hardware company not a software company and has little service for GitHub or the hobbyist.  The latest version of the software is not theirs but yours.  I have been using GitHub libraries for about a year now.  But, using a library and contributing to one are entirely different.  Although my project is getting more developed, my contributing to a GitHub library is fresh. I just started this contribution process this morning.  I am caught between clone and fork. I can wright my own code or contribute to yours.  But they seem to be two separate processes.  Or maybe I just have not found how to link my personal library to the official one. I am also using PlatformIO.  Although I cannot get it to edit GitHub.  So, I am editing from Google Chrome.

My project is a balancing robot.  I started with the firmware. It has the balance code in it.  I am studying and learning it.  Then gradually replacing their code with mine.  I have found a problem with MeGyro.  In BEGIN all values are initialized to zero.  In UPDATE the values are linked to gravity.  So, my robot is sitting on the table and I start the process.  All values are set to zero.  But my balancing robot is at 90 degrees. I have it set to balance around zero and shut down above 45 degrees.  So, it thinks it is at zero and runs off the table.  To properly initialize the angle, I have to loop through 500 UPDATES in SETUP.  That sets angle to 90 degrees.  A better way would be to get BEGIN to properly align the angle with gravity on startup.  I have started typing in the correction code.  The code correction is easy.  But the repositories are confusing.  MakeBlock has one.  You have one.  I have one.  Which edits went into which repository.  I am hoping to get you (a PRO) to assist me (a novice) to implement this small upgrade. 

I am currently trying to figure out the GitHub process.  Then I will type in all the code.  I will think about it some more.  I doubt that a first draft is sufficient.  The other choice would to test the code before contacting you.  I had to choose one.  Now, I can get back to the code.

**Comment by VorpalBlade** [comment]
Right. Nice to see you working on open source (though that is debatable, as there is no specified license for this code, it is not really open source).

However, I'd like to see a couple of things changed, and then I can merge it:
* Because I don't want a massive merge-job whenever Makeblock changes things I prefer to keep the deltas small, even if that means the code is badly formatted. This means that I'd like to see the formatting-only part of commit 00560c4 removed. (Believe me, if this wasn't a concern I'd make a lot of other changes as well!)
* There seems to be two separate concerns here in the same pull request. It is generally cleaner to do separate pull requests for separate things. This is something to think of in the future, I can handle it this time. But I would split it into (in the future):
  * One for the version number
  * One for the gyro changes.

Apart from that, great work.

**Comment by VorpalBlade** [comment]
I use Visual Studio Code with Platform IO, not the official Arduino IDE, so I'm unable to review the changes you made to those files. Also, I'm confused by the description change in library.properties. This library can be used for other things.

In fact I think I will just cherry pick the actual functional change to MeGyro at this point, and let you do the other things as separate pull requests per feature/bug.

**Comment by VorpalBlade** [comment]
I have opened a separate pull request, breaking out just the gyro changes, to demonstrate how this is preferably done. (We were all new to this once, and messed up). You can look at pull request #2.

As for the version number, it seems that "3.26" is the preferred form, used in many places, such as tags. It appears that only the revision history in the README uses the "3.2.6" form.

I'm not going to increment the version number, since I do not plan to make a release or a full fork. If you want to do that, you will have to maintain it yourself (and it should not go into this pull request).

**Comment by clplaneguy** [comment]
I am into the Git/GitHub/GitHub_Desktop/PlatformIO coordination process deeply for only 48 hours.  I should be able to have one private repository for my experiments and a public repository to send (Pull) polished code.  At this point they seem to be one and the same.  You are seeing experiments not intended for distribution and I cannot remove them.  The five lines of code only took a thought.  This publication/coordination process has rules that I do not know yet.  Perhaps it is time for me to have a fork(branch?) called "Private experiments" that you ignore.  Although my PRIVATE EXPERIMENNTS would have to be public so that PlatformIO can link to them.  Realize that I have not run this code yet.  I thought that patch_8 was private.  My bad.  But you are not seeing RobotLib or MakeBlock-Robot.  I will have to figure out exactly what they are.

My edits of the Arduino PID Library worked as expected.  
My edits of the MakeBlock library worked as expected.
Edited, uploaded and linked.  
Perhaps noone was watching.

**Comment by VorpalBlade** [comment]
Ah, I'm not familiar with Github Desktop, using different software personally (since Github desktop is (or at least was) not available for Linux).

When you make a pull request, any further commits to the same branch will automatically be included into the pull request. The idea is that you should create a new branch for every feature you develop/bug you fix, then make a pull request for that feature. You can add extra commits to said branch if it turns out that you need to modify your pull request.

Thus creating a new branch would indeed be the correct option here.

I wish you the best of luck in figuring out git. It can be a bit complicated, but it is well worth it once you get past the initial hurdle.

**Pull request closed without merging**
